version: '2'
services:
    c4sg-app:
        image: c4sg
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://c4sg-postgresql:5432/c4sg
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    c4sg-postgresql:
        extends:
            file: postgresql.yml
            service: c4sg-postgresql
